version: "3"

services:
  backend:
    image: stringconsultant/auto_deploy_test:latest
    command: gunicorn docker_demo.wsgi --bind 0.0.0.0:7888
    ports:
      - "7888:7888"
  nginx:
    image: nginx:latest
    ports:
      - "88:88"

    depends_on:
      - backend
