version: "3"

services:
  backend:
    image: stringconsultant/auto_deploy_test:latest
    command: gunicorn docker_demo.wsgi --bind 0.0.0.0:8005
    ports:
      - "8005:8005"
  nginx:
    image: nginx:latest
    ports:
      - "88:88"

    depends_on:
      - backend
