version: "3"

services:
  backend:
    build:
      context: ./backend
    command: gunicorn docker_demo.wsgi --bind 0.0.0.0:8005
    ports:
      - "8005:8005"
  nginx:
    image: nginx:latest
    ports:
      - "80:86"

    depends_on:
      - backend
